USE  CORPORATIVO

begin tran
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,2
           ,getdate()
           ,null
           ,'141891901'
           ,1)

INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,3
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,4
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,5
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,6
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,7
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,8
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,9
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,10
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,11
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,12
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,13
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,14
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,15
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,16
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,17
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,18
           ,getdate()
           ,null
           ,'141891901'
           ,1)
INSERT INTO [CORPORATIVO].[dbo].[tb_PersonalSucursal]
           ([Id_Personal]
           ,[Cod_SucursalBrinks]
           ,[FechaInicio]
           ,[FechaTermino]
           ,[Id_Autoriza]
           ,[Activo])
     VALUES
           ('244782779'
           ,19
           ,getdate()
           ,null
           ,'141891901'
           ,1)
Commit Tran
